### ISSUE TITLE
Transferd XP tokens in time reduced or gone

### ISSUE THREAD

**Issue by Lesserion** [elysium-project/tbc-bug-tracker#785]
On my horde character Nindie i have at the vanilla server an active XP token with 6 days left. After the transfer to TBC and no aditional playtime there is only 4 days left.

I also gifted Brylee a XP token, On the Vanilla server there is 19 hours left of it and on the TBC Realm the token is gone.

Something did not go right with the transfer. 

Will this be fixed somehow ?
On the discord chanels i have heard more players talking about this problem.

**Comment by Ziggy-QA** [comment]
Refunds were issued and the problem with them are now fixed.

**Comment by Lesserion** [comment]
Refunds were only issues when people bought the tomen in a certain period. These tokens were from before that, and i have not seen a refund on either of these two accounts. So in this case its still not settled i suppose ?
